name = "voicelab-mcp"
main = "dist/worker.js"
compatibility_date = "2024-09-23"
account_id = "77b418232c2446dc182a8a934a880d4f"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
